# 에러 핸들링

## try..catch와 에러 핸들링

> 에러는 언제든지 일어날 수 있다. 아무리 능숙해도
>
> 그리고 에러가 발생하면 스크립트는 죽게 된다.
>
> 그것을 방지하기 위해 try..catch가 있다

```javascript
try {
  // code
} catch (err) {
  // 에러 핸들링
}
```

- 동작의 중요점
  - 오직 런타임 에러에만 동작합니다
  - 동기적으로 동작합니다

### 에러 객체

- 내장 에러 전체와 애러 객체는 두 가지 주요 프로터티를 가집니다
  - name: 에러 이름, 정의되지 ㅇ낳은 변수 때문에 발생한 에러라면 `ReferenceError`
  - message: 에러 상세 내용을 담고 있는 문자 메시지
  - stack: 현재 호출 스택

필요시 직접 에러를 던질 수도 있다

```javascript
let json = '{ "age": 30 }'; // 불완전한 데이터

try {
  let user = JSON.parse(json); // <-- 에러 없음

  if (!user.name) {
    throw new SyntaxError("불완전한 데이터: 이름 없음"); // (*)
  }

  alert(user.name);
} catch (e) {
  alert("JSON Error: " + e.message); // JSON Error: 불완전한 데이터: 이름 없음
}

let json = '{ "age": 30 }'; // 불완전한 데이터
try {
  let user = JSON.parse(json);

  if (!user.name) {
    throw new SyntaxError("불완전한 데이터: 이름 없음");
  }

  blabla(); // 예상치 못한 에러

  alert(user.name);
} catch (e) {
  if (e instanceof SyntaxError) {
    alert("JSON Error: " + e.message);
  } else {
    throw e; // 에러 다시 던지기 (*)
  }
}
```

### finally

```javascript
try {
   ... 코드를 실행 ...
} catch(e) {
   ... 에러 핸들링 ...
} finally {
   ... 항상 실행 ...
}
```

finally는 어떤 경우에도 실행됩니다. return을 이용해 명시적으로 빠져나가려 해도 발생합니다

```javascript
function func() {
  try {
    return 1;
  } catch (e) {
    /* ... */
  } finally {
    alert("finally");
  }
}

alert(func()); // finally 안의 alert가 실행되고 난 후, 실행됨
```

## 커스텀 에러와 에러 확장

에러 슈도 코드를 한번 보자. 그리고 그 에러를 상속받아 하나 만들어보자

```javascript
// 자바스크립트 자체 내장 에러 클래스 Error의 '슈도 코드'
class Error {
  constructor(message) {
    this.message = message;
    this.name = "Error"; // (name은 내장 에러 클래스마다 다릅니다.)
    this.stack = <call stack>;  // stack은 표준은 아니지만, 대다수 환경이 지원합니다.
  }
}

class ValidationError extends Error {
  constructor(message) {
    super(message); // (1)
    this.name = "ValidationError"; // (2)
  }
}
```

한번 더 깊게 상속을 해보자

```javascript
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = "ValidationError";
  }
}

class PropertyRequiredError extends ValidationError {
  constructor(property) {
    super("No property: " + property);
    this.name = "PropertyRequiredError";
    this.property = property;
  }
}

// 사용법
function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new PropertyRequiredError("age");
  }
  if (!user.name) {
    throw new PropertyRequiredError("name");
  }

  return user;
}

// try..catch와 readUser를 함께 사용하면 다음과 같습니다.

try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No property: name
    alert(err.name); // PropertyRequiredError
    alert(err.property); // name
  } else if (err instanceof SyntaxError) {
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // 알려지지 않은 에러는 재던지기 합니다.
  }
}
```
